# Generated by Django 5.2.8 on 2025-11-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_distributorstatus_notification_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
